Made the workflow file also be aware of issues.

diff --git a/update_workflows/dace-updater.yml b/update_workflows/dace-updater.yml
--- a/update_workflows/dace-updater.yml
+++ b/update_workflows/dace-updater.yml
@@ -32,10 +32,17 @@ jobs:
           SOURCE_REPO="dace"
           SOURCE_OWNER="gridtools"
 
-          curl -L -v \
+          curl -L -v --fail-with-body \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.PKG_UPDATE_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${INDEX_ORGANIZATION}/${INDEX_REPO}/dispatches" \
             -d '{"event_type":"update_package_index","client_payload":{"source_repo":"'"${SOURCE_REPO}"'","source_org":"'"${SOURCE_OWNER}"'","dependency_ref":"'"${DEPENDENCY_REF}"'"}}'
+
+          if [ $? -ne 0 ]
+          then
+            echo "POST to '${INDEX_ORGANIZATION}:${INDEX_REPO}' failed.
+            exit 1
+          fi
+          exit 1
