Fixed errors.
- Added missing `"`.
- Improved error message.

diff --git a/update_workflows/dace-updater.yml b/update_workflows/dace-updater.yml
--- a/update_workflows/dace-updater.yml
+++ b/update_workflows/dace-updater.yml
@@ -39,10 +39,12 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${INDEX_ORGANIZATION}/${INDEX_REPO}/dispatches" \
             -d '{"event_type":"update_package_index","client_payload":{"source_repo":"'"${SOURCE_REPO}"'","source_org":"'"${SOURCE_OWNER}"'","dependency_ref":"'"${DEPENDENCY_REF}"'"}}'
+          CURL_RET=$?
 
-          if [ $? -ne 0 ]
+          if [ "${CURL_RET}" -ne 0 ]
           then
-            echo "POST to '${INDEX_ORGANIZATION}:${INDEX_REPO}' failed.
+            echo "POST to '${INDEX_ORGANIZATION}:${INDEX_REPO}' failed with error code '${CURL_RET}'"
             exit 1
           fi
-          exit 1
+
+          exit 0
