Implemented an install tester, not yet tested.

diff --git a/.github/workflows/update-python-pkg-index.yml b/.github/workflows/update-python-pkg-index.yml
--- a/.github/workflows/update-python-pkg-index.yml
+++ b/.github/workflows/update-python-pkg-index.yml
@@ -47,12 +47,32 @@ jobs:
         shell: bash
         run: |
           DEPENDENCY_REPO="${PWD}/${{ inputs.source_repo == '' && github.event.client_payload.source_repo || inputs.source_repo }}"
-          DIST_FOLDER="${PWD}/index_repo/${{ inputs.source_repo == '' && github.event.client_payload.source_repo || inputs.source_repo }}"
+          PACKAGE_BUILD_FOLDER="${PWD}/index_repo/build"
 
-          # TODO: Test if we can install it.
           cd "${DEPENDENCY_REPO}"
           python -m pip install build --user
-          python -m build --wheel --outdir "${DIST_FOLDER}"
+          python -m build --wheel --outdir "${PACKAGE_BUILD_FOLDER}"
+
+      - name: Test the distribution file.
+        shell: bash
+        run: |
+          PACKAGE_BUILD_FOLDER="${PWD}/index_repo/build"
+          DESTINATION_FOLDER="${PWD}/index_repo/${{ inputs.source_repo == '' && github.event.client_payload.source_repo || inputs.source_repo }}"
+          mkdir -p "${DESTINATION_FOLDER}"
+
+          readarray -t -d "" PACKAGE_FILES  < <(find "${PACKAGE_BUILD_FOLDER}" -type f -print0)
+          for I in ${!PACKAGE_FILES[@]}
+          do
+            PACKAGE_FILE="${PACKAGE_FILES[$I]}"
+            pip install --force-reinstall --upgrade --no-deps "${PACKAGE_FILE}"
+            if [ $? -ne 0 ]
+            then
+              echo "Failed to install package '${PACKAGE_FILE}'"
+              exit 3
+            fi
+            echo "Successfully tested '${PACKAGE_FILE}'"
+            cp -t "${DESTINATION_FOLDER}" "${PACKAGE_FILE}"
+          done
 
       - name: Rescan the package index and update the static `index.html` files.
         shell: bash
